'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronRight, Clock3, Flame, Minus, Phone, Plus, ShoppingBag, UtensilsCrossed, X } from 'lucide-react'
import type { MenuCategory, MenuProduct } from '@/services/menu'
import { useCart } from '@/hooks/use-cart'
import Link from 'next/link'

type Props = { categories: MenuCategory[]; products: MenuProduct[]; businessName: string; logoPath: string | null; phone: string | null; whatsapp: string | null; address: string | null; isOpen: boolean; acceptingOrders: boolean; todayHours: string | null; hoursSummary: string }
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })

export function Storefront({ categories, products, businessName, logoPath, phone, whatsapp, address, isOpen, acceptingOrders, todayHours, hoursSummary }: Props) {
  const [activeCategory, setActiveCategory] = useState(categories[0]?.id ?? '')
  const [selected, setSelected] = useState<MenuProduct | null>(null)
  const [quantity, setQuantity] = useState(1)
  const [added, setAdded] = useState(false)
  const [note, setNote] = useState('')
  const [selectedHoursDay, setSelectedHoursDay] = useState('')
  const { add, count } = useCart()
  const visibleCategories = categories.filter((category) => products.some((product) => product.category_id === category.id))
  const activeProducts = useMemo(() => products.filter((product) => !activeCategory || product.category_id === activeCategory), [products, activeCategory])
  const hoursEntries = hoursSummary ? hoursSummary.split(' · ').map((entry) => { const [day, ...timeParts] = entry.split(': '); return { day, hours: timeParts.join(': ') } }) : []
  const selectedHours = hoursEntries.find((entry) => entry.day === selectedHoursDay) ?? hoursEntries[0]

  function openProduct(product: MenuProduct) { if (!product.is_available) return; setSelected(product); setQuantity(1); setNote('') }
  function addProduct() { if (!selected) return; add(selected, quantity, note); setNote(''); setAdded(true); setSelected(null); window.setTimeout(() => setAdded(false), 2200) }

  return <main className="min-h-screen bg-[radial-gradient(circle_at_top,#fffaf5_0%,#f7f3ed_42%,#f1e9df_100%)] text-[#201a16]">
    <header className="relative overflow-hidden bg-[#1f1713] text-[#fff8ef]">
      <div aria-hidden="true" className="pointer-events-none absolute -right-24 -top-32 h-72 w-72 rounded-full bg-[#e76f27]/20 blur-3xl" />
      <div className="mx-auto max-w-6xl px-5 pb-10 pt-5 sm:px-8 sm:pb-16 sm:pt-7">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">{logoPath ? <img src={getProductImage(logoPath) ?? undefined} alt="Logo da loja" className="size-14 rounded-xl object-cover" /> : <span className="grid size-10 place-items-center rounded-xl bg-[#e76f27] shadow-lg shadow-[#e76f27]/20"><Flame className="size-5" fill="currentColor" /></span>}<span className="text-lg font-black tracking-tight">{businessName}</span></div>
          <Link href="/checkout" className="flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3.5 py-2 text-xs font-bold shadow-lg shadow-black/10 backdrop-blur transition hover:bg-white/15"><ShoppingBag className="size-4" /> <span>Meu pedido{count > 0 ? ` · ${count}` : ''}</span></Link>
        </div>
        <div className="mt-14 max-w-xl sm:mt-20"><p className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#ffb267]"><span className="size-2 rounded-full bg-[#66d49b] shadow-[0_0_12px_#66d49b]" /> Brasa acesa, sabor de verdade</p><h1 className="text-4xl font-black leading-[0.98] tracking-[-0.045em] sm:text-6xl">Seu churrasco,<br /><span className="text-[#ff9a4d]">do seu jeito.</span></h1><p className="mt-5 max-w-md text-sm leading-6 text-[#cdbeb0] sm:text-base">Espetos feitos na brasa, acompanhamentos caprichados e aquele sabor que pede repeteco.</p></div>
        <div className="mt-8 flex flex-wrap gap-2 text-xs font-bold"><Status label={isOpen ? 'Aberto agora' : 'Fechado agora'} positive={isOpen} /><Status label={acceptingOrders ? 'Aceitando pedidos' : 'Pedidos pausados'} positive={acceptingOrders} /><span className="flex items-center gap-1.5 rounded-full border border-white/10 bg-white/8 px-3 py-2 text-[#e7d8ca]"><Clock3 className="size-3.5" /> Hoje {todayHours ?? 'consulte os horários'}</span></div>
        <div aria-hidden="true" className="pointer-events-none absolute -bottom-20 right-[-4rem] hidden h-[25rem] w-[25rem] rounded-full border border-[#ff9a4d]/20 bg-[radial-gradient(circle_at_50%_38%,rgba(255,154,77,0.28),rgba(231,111,39,0.08)_34%,transparent_68%)] shadow-[0_0_100px_rgba(231,111,39,0.18)] sm:block lg:right-[5%]"><div className="absolute inset-10 rounded-full border border-[#ffb267]/15" /><div className="absolute left-1/2 top-1/2 grid size-28 -translate-x-1/2 -translate-y-1/2 rotate-[-8deg] place-items-center rounded-[2rem] border border-white/10 bg-white/10 text-[#ffb267] shadow-2xl backdrop-blur-sm"><Flame className="size-14" strokeWidth={1.5} /></div><span className="absolute bottom-16 left-1/2 -translate-x-1/2 whitespace-nowrap text-[10px] font-black uppercase tracking-[0.32em] text-[#ffb267]/70">feito na brasa</span></div>
      </div>
    </header>

    <section className="sticky top-0 z-20 border-b border-[#e8dfd5]/80 bg-[#fffaf5]/90 shadow-sm backdrop-blur-xl"><div className="mx-auto flex max-w-6xl gap-2 overflow-x-auto px-5 py-3 scrollbar-none sm:px-8">{visibleCategories.map((category) => <button key={category.id} onClick={() => setActiveCategory(category.id)} className={`shrink-0 rounded-full px-4 py-2.5 text-sm font-bold transition ${activeCategory === category.id ? 'bg-[#e76f27] text-white shadow-md shadow-[#e76f27]/20' : 'text-[#786a60] hover:bg-[#ece4da]'}`}>{category.name}</button>)}</div></section>

    <div className="mx-auto max-w-6xl px-5 py-9 sm:px-8 sm:py-12"><div className="mb-7 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#e76f27]">Feito na brasa</p><h2 className="mt-1 text-2xl font-black tracking-tight">{visibleCategories.find((c) => c.id === activeCategory)?.name ?? 'Nosso cardápio'}</h2></div><span className="text-xs font-semibold text-[#97887d]">{activeProducts.length} opções</span></div>
      {activeProducts.length === 0 ? <EmptyMenu /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{activeProducts.map((product) => <ProductCard key={product.id} product={product} onSelect={() => openProduct(product)} />)}</div>}
    </div>

    <footer className="border-t border-[#eadfd4] bg-[#211711] px-5 py-10 text-[#f7eee6] sm:px-8"><div className="mx-auto grid max-w-6xl gap-4 sm:grid-cols-3"><div><p className="font-black">{businessName}</p><p className="mt-2 text-sm text-[#cdbeb0]">{address || 'Endereço não informado'}</p></div><div><p className="text-xs font-bold uppercase tracking-widest text-[#ffb267]">Contato</p><p className="mt-2 text-sm text-[#cdbeb0]">{phone || 'Telefone não informado'}</p></div><div className="lg:-translate-x-10"><p className="text-xs font-bold uppercase tracking-widest text-[#ffb267]">Horários de funcionamento</p>{hoursEntries.length > 0 ? <div className="mt-3 space-y-2"><select aria-label="Escolha o dia para consultar o horário" value={selectedHours?.day ?? ''} onChange={(event) => setSelectedHoursDay(event.target.value)} className="w-full rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-sm font-semibold text-[#f7eee6] outline-none"><option value="" className="text-[#211711]">Escolha o dia</option>{hoursEntries.map((entry) => <option key={entry.day} value={entry.day} className="text-[#211711]">{entry.day}</option>)}</select>{selectedHours && <div className="flex items-center justify-between gap-3 border-b border-white/10 pb-1.5 pt-1 text-sm"><span className="font-semibold text-[#f7eee6]">{selectedHours.day}</span><span className="whitespace-nowrap text-right text-[#cdbeb0]">{selectedHours.hours}</span></div>}</div> : <p className="mt-2 text-sm text-[#cdbeb0]">{todayHours ? `Hoje: ${todayHours}` : 'Consulte os horários no painel'}</p>}</div></div></footer>
    {whatsapp && <a href={`https://wa.me/${whatsapp.replace(/\D/g, '')}`} target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp" className="fixed bottom-5 right-5 z-40 grid size-14 place-items-center rounded-full bg-[#25d366] text-white shadow-xl transition hover:scale-105 sm:bottom-6 sm:right-3"><Phone className="size-6" /></a>}
    {added && <div className="fixed bottom-5 left-1/2 z-40 flex -translate-x-1/2 items-center gap-2 rounded-full bg-[#201a16] px-5 py-3 text-sm font-bold text-white shadow-2xl"><span className="grid size-5 place-items-center rounded-full bg-[#66d49b]"><Check className="size-3.5 text-[#173322]" /></span>Adicionado ao pedido</div>}
    {selected && <ProductModal product={selected} quantity={quantity} setQuantity={setQuantity} note={note} setNote={setNote} onClose={() => setSelected(null)} onAdd={addProduct} />}
  </main>
}

function Status({ label, positive }: { label: string; positive: boolean }) { return <span className={`flex items-center gap-1.5 rounded-full border px-3 py-2 ${positive ? 'border-[#66d49b]/30 bg-[#66d49b]/10 text-[#a8ebc5]' : 'border-[#ff9a4d]/30 bg-[#ff9a4d]/10 text-[#ffc291]'}`}><span className={`size-1.5 rounded-full ${positive ? 'bg-[#66d49b]' : 'bg-[#ff9a4d]'}`} />{label}</span> }
function getProductImage(path: string | null) { if (!path) return null; if (path.startsWith('http')) return path; const baseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL; return baseUrl ? `${baseUrl}/storage/v1/object/public/product-images/${path}` : null }
function ProductCard({ product, onSelect }: { product: MenuProduct; onSelect: () => void }) { const image = getProductImage(product.image_path); return <article className="group overflow-hidden rounded-2xl border border-[#e8dfd5] bg-white shadow-[0_4px_20px_rgba(75,45,24,0.04)] transition hover:-translate-y-0.5 hover:shadow-lg"><div className="relative h-44 overflow-hidden bg-[#eaded0]">{image ? <img src={image} alt={product.name} className="size-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid size-full place-items-center bg-[radial-gradient(circle_at_40%_35%,#f8c68d,#d76c2c_52%,#542019)]"><UtensilsCrossed className="size-10 text-white/80" /></div>}<span className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-black uppercase tracking-wider text-[#e76f27]">Na brasa</span></div><div className="p-4"><h3 className="font-extrabold tracking-tight">{product.name}</h3><p className="mt-1 min-h-10 text-sm leading-5 text-[#89796e]">{product.description || 'Preparado na hora com ingredientes selecionados.'}</p><div className="mt-4 flex items-center justify-between"><span className="text-lg font-black text-[#2a211b]">{money.format(Math.round(Number(product.price) * 100) / 100)}</span><button type="button" onClick={onSelect} className="flex items-center gap-1 rounded-full bg-[#2a211b] px-3.5 py-2 text-xs font-bold text-white transition hover:bg-[#e76f27]">Adicionar <Plus className="size-3.5" /></button></div></div></article> }
function EmptyMenu() { return <div className="rounded-2xl border border-dashed border-[#d8cabc] bg-white/60 px-6 py-16 text-center"><UtensilsCrossed className="mx-auto size-8 text-[#c4b2a3]" /><h3 className="mt-4 font-bold">Cardápio em preparação</h3><p className="mt-1 text-sm text-[#89796e]">Os produtos desta categoria aparecerão aqui em breve.</p></div> }
function ProductModal({ product, quantity, setQuantity, note, setNote, onClose, onAdd }: { product: MenuProduct; quantity: number; setQuantity: (value: number) => void; note: string; setNote: (value: string) => void; onClose: () => void; onAdd: () => void }) { return <div className="fixed inset-0 z-30 flex items-end justify-center bg-[#201a16]/60 p-0 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={`Adicionar ${product.name}`}><div className="w-full max-w-lg rounded-t-3xl bg-[#fffaf5] p-6 shadow-2xl sm:rounded-3xl">{getProductImage(product.image_path) && <img src={getProductImage(product.image_path) as string} alt="" className="mb-5 h-40 w-full rounded-2xl object-cover" />}<div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-[#e76f27]">Seu pedido</p><h2 className="mt-1 text-2xl font-black">{product.name}</h2></div><button type="button" onClick={onClose} aria-label="Fechar" className="rounded-full p-2 text-[#89796e] hover:bg-[#efe5da]"><X className="size-5" /></button></div><p className="mt-3 text-sm leading-6 text-[#89796e]">{product.description || 'Preparado na hora com ingredientes selecionados.'}</p><div className="mt-7 flex items-center justify-between rounded-2xl bg-[#f1e8de] p-3"><span className="text-sm font-bold">Quantidade</span><div className="flex items-center gap-3"><button type="button" onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Diminuir quantidade" className="grid size-9 place-items-center rounded-full bg-white"><Minus className="size-4" /></button><strong>{quantity}</strong><button type="button" onClick={() => setQuantity(Math.min(99, quantity + 1))} aria-label="Aumentar quantidade" className="grid size-9 place-items-center rounded-full bg-white"><Plus className="size-4" /></button></div></div><label className="mt-5 block text-sm font-bold" htmlFor="note">Observação <span className="font-normal text-[#a79689]">(opcional)</span></label><textarea id="note" value={note} onChange={(event) => setNote(event.target.value)} placeholder="Ex.: bem passado, sem cebola..." className="mt-2 min-h-20 w-full resize-none rounded-xl border border-[#e3d7cc] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#e76f27]" /><button type="button" onClick={onAdd} className="mt-6 flex w-full items-center justify-between rounded-xl bg-[#e76f27] px-5 py-4 font-black text-white shadow-lg shadow-[#e76f27]/20"><span>Adicionar ao pedido</span><span>{money.format(product.price * quantity)} <ArrowRight className="ml-1 inline size-4" /></span></button></div></div> }
